### ISSUE TITLE
Handle All failure possibilities in client api calls

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [brainvest/dscribe#2]
Currently almost all api calls do not handle failures. They just suppose everything will succeed and do give any feedback to the user.

We need to choose a consistent feedback mechanism, and then apply it to all user actions.

**Comment by arashbahreini** [comment]
I'm working on this issue.

**Comment by arashbahreini** [comment]
Also logical errors in GenerateCode action should be refactor in both side ( Server / Client )

**Comment by N1MA** [comment]
Where are we on this? what else do we need to consider this issue dealt with?

**Comment by arashbahreini** [comment]
This issue is almost done. the remain things are as the list of below. 

1. Call snackbar in interceptor instead of each component individually. 
2. Separate Errors with status codes 500 and 400. In bad request errors, the message should be shown below of the form field and in case of Internal server error, the message should present by snackbar. 

I will perform these actions in the current weekend.
