### ISSUE TITLE
Migration does not set Identity = true for Id fields 

### ISSUE THREAD

**Issue by arashbahreini** [brainvest/dscribe#41]
This issue can be handle by [This link](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/73)

**Comment by arashbahreini** [comment]
Currently, I am setting Id fields to identity which is wrong as well as this making incompatibility with migration history table.

**Comment by AlirezaHaghshenas** [comment]
Ad mentioned [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers), when generating migrations, the EF core tooling uses the current provider. There might be additional hand-crafted migration code required to maintain compatibility with other providers.

The current migration works well for MySql and SqlServer, but we need to be cautious, as new auto-generated migrations need manual tuning as well.

Out current problem with migrations is that for some reason (most probably a bug in EF tooling) new migrations tend to delete some seed data and recreate it (and will fail because the seed data to be deleted is referenced by some foreign keys).
